"""0 Create payment db

Revision ID: 4c7ed4dbd128
Revises: 
Create Date: 2023-05-18 01:37:11.764317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c7ed4dbd128'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('payment_fee', sa.FLOAT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=500), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
