{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-service.fullname" . }}-secret
  labels:
    {{- include "spring-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
