"""0 Create cart db

Revision ID: 3042e04d6ba6
Revises: 
Create Date: 2023-05-18 11:20:32.247623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3042e04d6ba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=500), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('cart_id', sa.BIGINT(), nullable=True),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    op.drop_table('cart')
    # ### end Alembic commands ###
