use Icecream;

insert into users (username, email, password, status) values ("Gulag0","gulag0@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag1","gulag1@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag2","gulag2@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag3","gulag3@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag4","gulag4@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag5","gulag5@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag6","gulag6@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag7","gulag7@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag8","gulag8@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag9","gulag9@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag10","gulag10@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag11","gulag11@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag12","gulag12@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag13","gulag13@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag14","gulag14@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag15","gulag15@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag16","gulag16@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag17","gulag17@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag18","gulag18@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag19","gulag19@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag20","gulag20@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag21","gulag21@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag22","gulag22@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag23","gulag23@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag24","gulag24@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag25","gulag25@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag26","gulag26@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag27","gulag27@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag28","gulag28@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag29","gulag29@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag30","gulag30@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag31","gulag31@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag32","gulag32@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag33","gulag33@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag34","gulag34@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag35","gulag35@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag36","gulag36@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag37","gulag37@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag38","gulag38@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag39","gulag39@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag40","gulag40@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag41","gulag41@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag42","gulag42@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag43","gulag43@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag44","gulag44@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag45","gulag45@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag46","gulag46@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag47","gulag47@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag48","gulag48@gmail.com", "1234","1");
insert into users (username, email, password, status) values ("Gulag49","gulag49@gmail.com", "1234","1");

insert into user_role (user_id, role_id) values ("6","3");
insert into user_role (user_id, role_id) values ("7","3");
insert into user_role (user_id, role_id) values ("8","3");
insert into user_role (user_id, role_id) values ("9","3");
insert into user_role (user_id, role_id) values ("10","3");
insert into user_role (user_id, role_id) values ("11","3");
insert into user_role (user_id, role_id) values ("12","3");
insert into user_role (user_id, role_id) values ("13","3");
insert into user_role (user_id, role_id) values ("14","3");
insert into user_role (user_id, role_id) values ("15","3");
insert into user_role (user_id, role_id) values ("16","3");
insert into user_role (user_id, role_id) values ("17","3");
insert into user_role (user_id, role_id) values ("18","3");
insert into user_role (user_id, role_id) values ("19","3");
insert into user_role (user_id, role_id) values ("20","3");
insert into user_role (user_id, role_id) values ("21","3");
insert into user_role (user_id, role_id) values ("22","3");
insert into user_role (user_id, role_id) values ("23","3");
insert into user_role (user_id, role_id) values ("24","3");
insert into user_role (user_id, role_id) values ("25","3");
insert into user_role (user_id, role_id) values ("26","3");
insert into user_role (user_id, role_id) values ("27","3");
insert into user_role (user_id, role_id) values ("28","3");
insert into user_role (user_id, role_id) values ("29","3");
insert into user_role (user_id, role_id) values ("30","3");
insert into user_role (user_id, role_id) values ("31","3");
insert into user_role (user_id, role_id) values ("32","3");
insert into user_role (user_id, role_id) values ("33","3");
insert into user_role (user_id, role_id) values ("34","3");
insert into user_role (user_id, role_id) values ("35","3");
insert into user_role (user_id, role_id) values ("36","3");
insert into user_role (user_id, role_id) values ("37","3");
insert into user_role (user_id, role_id) values ("38","3");
insert into user_role (user_id, role_id) values ("39","3");
insert into user_role (user_id, role_id) values ("40","3");
insert into user_role (user_id, role_id) values ("41","3");
insert into user_role (user_id, role_id) values ("42","3");
insert into user_role (user_id, role_id) values ("43","3");
insert into user_role (user_id, role_id) values ("44","3");
insert into user_role (user_id, role_id) values ("45","3");
insert into user_role (user_id, role_id) values ("46","3");
insert into user_role (user_id, role_id) values ("47","3");
insert into user_role (user_id, role_id) values ("48","3");
insert into user_role (user_id, role_id) values ("49","3");
insert into user_role (user_id, role_id) values ("50","3");
insert into user_role (user_id, role_id) values ("51","3");
insert into user_role (user_id, role_id) values ("52","3");
insert into user_role (user_id, role_id) values ("53","3");
insert into user_role (user_id, role_id) values ("54","3");
insert into user_role (user_id, role_id) values ("55","3");

insert into faq (question, answer) values ("Question 0 asked?", "Answer: 0");
insert into faq (question, answer) values ("Question 1 asked?", "Answer: 1");
insert into faq (question, answer) values ("Question 2 asked?", "Answer: 2");
insert into faq (question, answer) values ("Question 3 asked?", "Answer: 3");
insert into faq (question, answer) values ("Question 4 asked?", "Answer: 4");
insert into faq (question, answer) values ("Question 5 asked?", "Answer: 5");
insert into faq (question, answer) values ("Question 6 asked?", "Answer: 6");
insert into faq (question, answer) values ("Question 7 asked?", "Answer: 7");
insert into faq (question, answer) values ("Question 8 asked?", "Answer: 8");
insert into faq (question, answer) values ("Question 9 asked?", "Answer: 9");
insert into faq (question, answer) values ("Question 10 asked?", "Answer: 10");
insert into faq (question, answer) values ("Question 11 asked?", "Answer: 11");
insert into faq (question, answer) values ("Question 12 asked?", "Answer: 12");
insert into faq (question, answer) values ("Question 13 asked?", "Answer: 13");
insert into faq (question, answer) values ("Question 14 asked?", "Answer: 14");
insert into faq (question, answer) values ("Question 15 asked?", "Answer: 15");
insert into faq (question, answer) values ("Question 16 asked?", "Answer: 16");
insert into faq (question, answer) values ("Question 17 asked?", "Answer: 17");
insert into faq (question, answer) values ("Question 18 asked?", "Answer: 18");
insert into faq (question, answer) values ("Question 19 asked?", "Answer: 19");
insert into faq (question, answer) values ("Question 20 asked?", "Answer: 20");
insert into faq (question, answer) values ("Question 21 asked?", "Answer: 21");
insert into faq (question, answer) values ("Question 22 asked?", "Answer: 22");
insert into faq (question, answer) values ("Question 23 asked?", "Answer: 23");
insert into faq (question, answer) values ("Question 24 asked?", "Answer: 24");
insert into faq (question, answer) values ("Question 25 asked?", "Answer: 25");
insert into faq (question, answer) values ("Question 26 asked?", "Answer: 26");
insert into faq (question, answer) values ("Question 27 asked?", "Answer: 27");
insert into faq (question, answer) values ("Question 28 asked?", "Answer: 28");
insert into faq (question, answer) values ("Question 29 asked?", "Answer: 29");
insert into faq (question, answer) values ("Question 30 asked?", "Answer: 30");
insert into faq (question, answer) values ("Question 31 asked?", "Answer: 31");
insert into faq (question, answer) values ("Question 32 asked?", "Answer: 32");
insert into faq (question, answer) values ("Question 33 asked?", "Answer: 33");
insert into faq (question, answer) values ("Question 34 asked?", "Answer: 34");
insert into faq (question, answer) values ("Question 35 asked?", "Answer: 35");
insert into faq (question, answer) values ("Question 36 asked?", "Answer: 36");
insert into faq (question, answer) values ("Question 37 asked?", "Answer: 37");
insert into faq (question, answer) values ("Question 38 asked?", "Answer: 38");
insert into faq (question, answer) values ("Question 39 asked?", "Answer: 39");
insert into faq (question, answer) values ("Question 40 asked?", "Answer: 40");
insert into faq (question, answer) values ("Question 41 asked?", "Answer: 41");
insert into faq (question, answer) values ("Question 42 asked?", "Answer: 42");
insert into faq (question, answer) values ("Question 43 asked?", "Answer: 43");
insert into faq (question, answer) values ("Question 44 asked?", "Answer: 44");
insert into faq (question, answer) values ("Question 45 asked?", "Answer: 45");
insert into faq (question, answer) values ("Question 46 asked?", "Answer: 46");
insert into faq (question, answer) values ("Question 47 asked?", "Answer: 47");
insert into faq (question, answer) values ("Question 48 asked?", "Answer: 48");
insert into faq (question, answer) values ("Question 49 asked?", "Answer: 49");

insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/0/200/200", "product0", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/1/200/200", "product1", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/2/200/200", "product2", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/3/200/200", "product3", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/4/200/200", "product4", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/5/200/200", "product5", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/6/200/200", "product6", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/7/200/200", "product7", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/8/200/200", "product8", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/9/200/200", "product9", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/10/200/200", "product10", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/11/200/200", "product11", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/12/200/200", "product12", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/13/200/200", "product13", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/14/200/200", "product14", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Electronic book", "https://picsum.photos/id/15/200/200", "product15", "4.13", "1", "1");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/16/200/200", "product16", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/17/200/200", "product17", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/18/200/200", "product18", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/19/200/200", "product19", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/20/200/200", "product20", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/21/200/200", "product21", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/22/200/200", "product22", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/23/200/200", "product23", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/24/200/200", "product24", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/25/200/200", "product25", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/26/200/200", "product26", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/27/200/200", "product27", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/28/200/200", "product28", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/29/200/200", "product29", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/30/200/200", "product30", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Math book", "https://picsum.photos/id/31/200/200", "product31", "5.9", "1", "2");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/32/200/200", "product32", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/33/200/200", "product33", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/34/200/200", "product34", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/35/200/200", "product35", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/36/200/200", "product36", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/37/200/200", "product37", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/38/200/200", "product38", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/39/200/200", "product39", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/40/200/200", "product40", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/41/200/200", "product41", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/42/200/200", "product42", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/43/200/200", "product43", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/44/200/200", "product44", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/45/200/200", "product45", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/46/200/200", "product46", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Another computer science book", "https://picsum.photos/id/47/200/200", "product47", "5.21", "1", "3");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/48/200/200", "product48", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/49/200/200", "product49", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/50/200/200", "product50", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/51/200/200", "product51", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/52/200/200", "product52", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/53/200/200", "product53", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/54/200/200", "product54", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/55/200/200", "product55", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/56/200/200", "product56", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/57/200/200", "product57", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/58/200/200", "product58", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/59/200/200", "product59", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/60/200/200", "product60", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/61/200/200", "product61", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/62/200/200", "product62", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/63/200/200", "product63", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/64/200/200", "product64", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/65/200/200", "product65", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/66/200/200", "product66", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/67/200/200", "product67", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/68/200/200", "product68", "1.15", "1", "4");
insert into products (description,image,name,price,status,category_id) values ("Economic book", "https://picsum.photos/id/69/200/200", "product69", "1.15", "1", "4");
