"""0 Create order db

Revision ID: a73bd1fa0215
Revises: 
Create Date: 2023-05-18 11:21:45.399255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a73bd1fa0215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tbl',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=True),
    sa.Column('delivery_fee', sa.FLOAT(), nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('delivery_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=500), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('payment_id', sa.BIGINT(), nullable=True),
    sa.Column('address_id', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.NullType(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('product_price', sa.FLOAT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('order_tbl')
    # ### end Alembic commands ###
