import { type Metadata } from 'next'
import { type ReactNode, type FC } from 'react'

import '@/global.css'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

type Props = {
  children: ReactNode
}

const RootLayout: FC<Props> = ({ children }) => (
  <html lang="en">
    <body>{children}</body>
  </html>
)

export default RootLayout
