# bitnami/postgresql - dedicated instance for `consul` (transactional service)
auth:
  username: consul
  database: consul
  existingSecret: "consul-postgresql-secret"   # keys: postgres-password, password
primary:
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests: { cpu: 250m, memory: 512Mi }
    limits:   { cpu: 1000m, memory: 1Gi }
