"""Create feedback db

Revision ID: 20dc9e0ee4f0
Revises:
Create Date: 2023-05-17 11:47:37.006076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20dc9e0ee4f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('rating_start', sa.FLOAT(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=500), nullable=True),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
