"""0 Init lookup db

Revision ID: c554ce33ac6f
Revises: 
Create Date: 2023-08-03 00:49:47.726717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c554ce33ac6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('city', sa.VARCHAR(length=200), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.VARCHAR(length=500), nullable=True),
    sa.Column('filepath', sa.VARCHAR(length=200), nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('address')
    # ### end Alembic commands ###
