"""0 Create product db

Revision ID: 987e9ce9e0a5
Revises: 
Create Date: 2023-05-18 11:22:07.013285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '987e9ce9e0a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=True),
    sa.Column('meta_keyword', sa.VARCHAR(length=200), nullable=True),
    sa.Column('meta_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('media_id', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('brief_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('specification', sa.VARCHAR(length=500), nullable=True),
    sa.Column('sku', sa.VARCHAR(length=200), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('stock_quantity', sa.INTEGER(), nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('meta_keyword', sa.VARCHAR(length=200), nullable=True),
    sa.Column('meta_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.Column('media_id', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_modified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
