-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.11-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             10.3.0.5771
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for icecream
CREATE DATABASE IF NOT EXISTS `icecream` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `icecream`;

-- Dumping structure for table icecream.admin
CREATE TABLE IF NOT EXISTS `admin` (
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.admin: ~1 rows (approximately)
/*!40000 ALTER TABLE `admin` DISABLE KEYS */;
INSERT INTO `admin` (`username`, `password`) VALUES
	('admin', 'admin');
/*!40000 ALTER TABLE `admin` ENABLE KEYS */;

-- Dumping structure for table icecream.customer
CREATE TABLE IF NOT EXISTS `customer` (
  `customer_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `password` varchar(1024) NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `address` varchar(100) DEFAULT NULL,
  `phone_number` varchar(50) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `gender` tinyint(1) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `avatar` varchar(2048) DEFAULT NULL,
  `expired_date` date NOT NULL,
  `enable_status` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`customer_id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.customer: ~10 rows (approximately)
/*!40000 ALTER TABLE `customer` DISABLE KEYS */;
INSERT INTO `customer` (`customer_id`, `username`, `password`, `fullname`, `address`, `phone_number`, `email`, `gender`, `birthday`, `avatar`, `expired_date`, `enable_status`) VALUES
	(1, 'user1', '8l9Dp3HQloE=', 'Name 1', '123 Pasteur', '0901234567', 'name1@icecream.com', 1, '1987-01-01', 'images/uploaded/noavatar.gif', '2012-12-25', 1),
	(2, 'user3', '8l9Dp3HQloE=', 'Name 2', '456 Alexandre de Rhodes', '0911234567', 'name2@icecream.com', 1, '1991-01-01', 'images/uploaded/noavatar.gif', '2012-12-12', 1),
	(3, 'user2', '8l9Dp3HQloE=', 'Name 3', '789 Yersin', '0921234567', 'name3@icecream.com', 1, '1990-01-01', 'images/uploaded/noavatar.gif', '2012-12-12', 1),
	(4, 'user5', 'Cuwus/jwiqVUDOdgDW8Lgw==', 'Im Yoona', 'Seoul - Korea', '091234567', 'yoona90@gmail.com', 0, '1990-10-05', 'images/uploaded/yoona.gif', '2012-12-12', 1),
	(5, 'lovely', 'Cuwus/jwiqVUDOdgDW8Lgw==', 'NoName', 'Seoul - Korea', '0912345678', 'noname@gmail.com', 0, '1990-10-10', 'images/uploaded/noname.gif', '2013-02-11', 1),
	(6, 'ILoveVietNam', 'Cuwus/jwiqVUDOdgDW8Lgw==', 'Name 6', 'Ho Chi Minh', '0912345679', 'ilovevn@gmail.com', 1, '1990-10-11', 'images/uploaded/noname.gif', '2013-02-11', 1),
	(7, 'ILoveHoChiMinh', 'Cuwus/jwiqVUDOdgDW8Lgw==', 'Name 7', 'Ho Chi Minh', '0932345659', 'ilovehochiminh@gmail.com', 1, '1985-10-11', 'images/uploaded/yoona.jpg', '2014-02-11', 1),
	(8, 'ILoveHue', 'Cuwus/jwiqVUDOdgDW8Lgw==', 'Name 8', 'Ho Chi Minh', '0912345659', 'ilovehue@gmail.com', 1, '1991-10-11', 'images/uploaded/0.jpg', '2014-02-11', 1),
	(9, 'ILoveYou', 'Cuwus/jwiqVUDOdgDW8Lgw==', 'Need Some One', 'Ho Chi Minh', '0912345609', 'iloveyou@gmail.com', 1, '1990-10-11', 'images/uploaded/yoona.gif', '2014-02-11', 1),
	(10, 'loveyouloveme', 'Cuwus/jwiqVUDOdgDW8Lgw==', 'Need a love', 'Ho Chi Minh', '0913345659', 'needalove@gmail.com', 1, '1999-10-11', 'images/uploaded/yoona.gif.jpg', '2012-02-02', 1);
/*!40000 ALTER TABLE `customer` ENABLE KEYS */;

-- Dumping structure for table icecream.faq
CREATE TABLE IF NOT EXISTS `faq` (
  `faq_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `question` text NOT NULL,
  `answer` text NOT NULL,
  PRIMARY KEY (`faq_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.faq: ~5 rows (approximately)
/*!40000 ALTER TABLE `faq` DISABLE KEYS */;
INSERT INTO `faq` (`faq_id`, `question`, `answer`) VALUES
	(1, 'Where can I get coupons for Parlor products?', 'Occasionally we offer coupons and samples on our website and Facebook page.'),
	(2, 'Do your products contain allergens or gluten?', 'Some products do contain allergens, including gluten. However, most of our ice creams and frozen dairy desserts are naturally gluten free. We are currently updating our packaging to make it easy for you to identify all of our naturally gluten free variants. It is our policy that when any of the eight most common allergens (milk, eggs, fish, wheat, tree nuts, peanuts, soybeans and crustaceans) occur in any of our products they will be listed inside the ingredient statement in plain language.'),
	(3, 'How Can I Buy Book Online?', 'You Should Login to The Member Page and Leave your Personal infomation there .Our deliver service base on this.'),
	(4, 'Is my daughter safe on Parlor Icecream? ', 'User safety is our most important concern. Always Icecream is using a wide range of methods and processes to ensure user safety and privacy. The site is content is continuously scanned for inappropriate content using both software and manual reviews. Users can also report any concerns or problems they encounter to Always Icecream staff. Furthermore, self-policing mechanisms are in place to encourage proper behavior and etiquette. Lastly, parents receive regular email reports about the activities and learning progress of their daughter. '),
	(5, 'If my recipe is Prized what way i receive my prize money?', 'You can go direct to Parlor Shop or your banking...');
/*!40000 ALTER TABLE `faq` ENABLE KEYS */;

-- Dumping structure for table icecream.feedback
CREATE TABLE IF NOT EXISTS `feedback` (
  `feedback_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `fullname` varchar(50) DEFAULT 'guest',
  `title` varchar(100) NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY (`feedback_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.feedback: ~5 rows (approximately)
/*!40000 ALTER TABLE `feedback` DISABLE KEYS */;
INSERT INTO `feedback` (`feedback_id`, `fullname`, `title`, `content`) VALUES
	(1, 'User1', 'what a wonderful recipe', 'the recipes are so great,I can make Ice-Creame by myself'),
	(2, 'User2', 'Thanks alot', 'Thanks very much .After became members i have been seen the recipe'),
	(3, 'User3', 'Dear', 'Love the Ice Creame recipe.All Best Ice cream in town every time'),
	(4, 'User4', 'Best Vani cream', 'The Ice Cream is great and they have a wide variety of flavours, amazing milkshakes and desserts.'),
	(5, 'User3', 'Dear', 'Love the Ice Creame recipe.All Best Ice cream in town every time');
/*!40000 ALTER TABLE `feedback` ENABLE KEYS */;

-- Dumping structure for table icecream.online_order
CREATE TABLE IF NOT EXISTS `online_order` (
  `order_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `contact` varchar(1024) NOT NULL,
  `address` varchar(2048) NOT NULL,
  `book_cost` float NOT NULL,
  `paying_option` varchar(100) NOT NULL,
  `order_date` datetime NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.online_order: ~0 rows (approximately)
/*!40000 ALTER TABLE `online_order` DISABLE KEYS */;
/*!40000 ALTER TABLE `online_order` ENABLE KEYS */;

-- Dumping structure for table icecream.prize_history
CREATE TABLE IF NOT EXISTS `prize_history` (
  `user_recipe_id` bigint(20) NOT NULL,
  `enable_status` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_recipe_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.prize_history: ~3 rows (approximately)
/*!40000 ALTER TABLE `prize_history` DISABLE KEYS */;
INSERT INTO `prize_history` (`user_recipe_id`, `enable_status`) VALUES
	(1, 0),
	(2, 0),
	(3, 0);
/*!40000 ALTER TABLE `prize_history` ENABLE KEYS */;

-- Dumping structure for table icecream.recipe
CREATE TABLE IF NOT EXISTS `recipe` (
  `recipe_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `image` varchar(100) NOT NULL,
  `desciption` text NOT NULL,
  `details` text NOT NULL,
  `author` varchar(50) NOT NULL,
  `view_number` bigint(20) NOT NULL DEFAULT 1,
  `upload_date` date NOT NULL,
  `enable_status` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`recipe_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.recipe: ~20 rows (approximately)
/*!40000 ALTER TABLE `recipe` DISABLE KEYS */;
INSERT INTO `recipe` (`recipe_id`, `name`, `image`, `desciption`, `details`, `author`, `view_number`, `upload_date`, `enable_status`) VALUES
	(1, 'Banana chocolate chip ice cream', 'images/Banana chocolate chip ice cream(300x300).jpg', '\n2/3 cup sugar.\n2 large eggs.\n1 1/2 tablespoons all-purpose flour.\n1/8 teaspoon salt.\n1 1/4 cups milk.\n2 large very ripe bananas.\n1 cup light cream.\n1 teaspoon vanilla extract.\n2 tablespoons banana liqueur', '\nStep 1: In a medium mixing bowl, beat the sugar into the eggs until thickened and pale yellow. Beat in the flour and salt. Set aside.\nStep 2: Bring the milk to a boil in a heavy medium saucepan. Slowly beat the hot milk into the eggs and sugar. Pour the entire mixture back into the pan and place over low heat. Stir constantly with a whisk or wooden spoon until the custard thickens slightly. Be careful not to let the mixture boil or the eggs will scramble. Remove from the heat and pour the custard through a strainer into a large, clean bowl.\nStep 3: Mash the bananas with a potato masher until they are creamy, or puree them in a food processor. Add the banana puree to the hot custard and mix well. Allow the banana custard to cool slightly. Stir in the cream, vanilla.\nStep 4: Cover and refrigerate until cold or overnight. (My kids have never let me chill anything overnight, so I speed up the cooling process with an ice bath. Just make sure your mixture is completely chilled before adding to the ice cream machine).\nStep 5: Stir the chilled custard, and then freeze in 1 or 2 batches in your ice cream machine according to the manufacturer’s instructions.\nStep 6: When the ice cream is semi-frozen, add ½ cup of semi-sweet chocolate chips to the machine and let the machine mix the chocolate.\nStep 7: When finished, the ice cream will be soft but ready to eat. For firmer ice cream, transfer to a freezer-safe container and freeze at least 2 hours.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(2, 'Banana ice cream', 'images/Banana ice cream(300x300).jpg', '\n6 (approximately 2 1/4 pounds) ripe bananas.\n1 tablespoon fresh squeezed lemon juice.\n3/4 cup light corn syrup.\n1 vanilla bean, scraped.\n1 1/2 cups heavy cream', '\n1.Place bananas in freezer and freeze overnight.\n2.Remove bananas from freezer and allow to thaw for 45 minutes to 1 hour.\n3.Peel bananas and place in bowl of food processor along with the lemon juice.\n4.Process for 10 to 15 seconds.\n5.Add corn syrup and vanilla bean seeds and turn processor on.\n6.Slowly pour in the heavy cream. Process until smooth.\n7.Chill mixture in refrigerator until it reaches 40 degrees.\n8.Transfer mixture to an ice cream maker and process according to manufacturers instructions.\n9.Place mixture in an airtight container and freeze for 3 to 6 hours before serving.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(3, 'Blackcurrant ice cream', 'images/Blackcurrant ice cream(300x300).jpg', '\n1 lb (450 g) fresh or frozen blackcurrants, defrosted if frozen.\n6 oz (175 g) sugar.\n10 fl oz (275 ml) double cream', '\n1.Theres no need to take the stalks off the blackcurrants, just pile them, about one third of a pound (5 oz/150 g) at a time, into the sieve set over a mixing bowl, and mash like mad with a wooden spoon until you have extracted all the pulp and only the stalks, pips and skins are left in the sieve.\n2.Now place the sugar and 5 fl oz (150 ml) water in a saucepan over a medium heat, stir until all the sugar crystals have dissolved, then let it come to the boil, and boil for 3 minutes exactly. Then remove from the heat and stir the syrup into the fruit pulp. Whip the cream until it just begins to thicken. Be careful not to overwhip: it mustnt be thick, just floppy. Fold the cream into the fruit mixture until thoroughly blended. Pour it into the polythene box, and freeze in a freezer or in the ice-making compartment of a fridge turned to its coldest setting.\n3.As soon as the mixture begins to set (after about 3 hours) turn it out into a bowl and beat thoroughly. Then return it to the freezer (in the box) until set – about another 3 hours. Remove to the main part of the fridge about an hour before serving.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(4, 'Butterscotch ice cream', 'images/Butterscotch ice cream(300x300).jpg', '\n1 cup firmly packed brown sugar.\n2 tablespoons butter.\n1 tablespoon vanilla.\n1 1/2 cups whipping cream.\n2 cups half-and-half (light cream).\n6 large egg yolks', '\n1. In a 1- to 2-quart pan over medium heat, stir brown sugar, butter, and vanilla until butter is melted, sugar is dissolved, and mixture is bubbly, 3 to 4 minutes. Whisk in 1/2 cup whipping cream until smooth; remove butterscotch mixture from heat.\n2. In a 3- to 4-quart pan over medium-high heat, combine remaining 1 cup whipping cream and the half-and-half; bring to a simmer.\n3. Meanwhile, in a bowl, beat egg yolks to blend. Whisk 1/2 cup of the warm cream mixture into egg yolks, then pour egg yolk mixture into pan with cream. Stir constantly over low heat just until mixture is slightly thickened, 2 to 4 minutes. Immediately remove from heat.\n4. Pour through a fine strainer into a clean bowl and whisk in butterscotch mixture. Chill until cold, stirring occasionally, about 2 hours; or cover and chill up to 1 day.\n5. Freeze mixture in an ice cream maker according to manufacturers instructions. Serve softly frozen, or transfer ice cream to an airtight container and freeze until firm, at least 6 hours or up to 1 week.Nutritional analysis is per 1/2 cup.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(5, 'Cashew Caramel crunch ice cream', 'images/Cashew Caramel crunch ice cream(300x300).jpg', '\n1/2 cup blanched almonds, toasted.\n1/2 cup caster sugar.\n2 litres vanilla ice-cream, softened.\n380g can Top n Fill Caramel.\n200g dark chocolate melts.\n60g copha', '\nStep 1: Line an oven tray with baking paper. Sprinkle almonds over tray. Combine sugar and 1/2 cup warm water in a saucepan over low heat. Simmer, stirring, for 3 minutes. Increase heat to high. Bring to the boil. Boil, without stirring, for 10 minutes or until mixture is golden. Remove from heat. Stand for 1 minute to allow bubbles to subside. Pour over almonds. Allow to cool until set.\nStep 2: Peel baking paper from almond mixture. Cut almond mixture into small pieces. Combine ice-cream and almond mixture in a bowl. Fold caramel through ice-cream. Return ice-cream to container. Place in freezer overnight or until firm.\nStep 3: Scoop small balls of ice-cream onto a tray lined with baking paper. Freeze for 30 minutes.\nStep 4: Meanwhile, place chocolate and copha in a heatproof, microwave-safe bowl. Microwave on high (100%) for 1 to 2 minutes, stirring every minute with a metal spoon, or until smooth. Set aside. Allow to cool slightly.\nStep 5: Using a fork, dip the ice-cream balls in chocolate mixture. Return to prepared tray. Place in freezer for 30 minutes or until chocolate mixture is set. Serve.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(6, 'Cherry ice cream', 'images/Cherry ice cream(300x300).jpg', '\n2 cups (500 ml) heavy cream.\n1 cup (250 ml) whole milk.\n3/4 cup (150 g) granulated sugar.\nPinch of salt.\n1 vanilla bean.\n1 tsp. vanilla extract.\nAbout 2 ½ cups fresh cherries (will be 2 cups when pitted and quartered)', '\n1.In a medium saucepan, heat 1 cup of the cream, sugar, and salt.\n2.Split the vanilla bean in half lengthwise with knife and scrape the seeds with spoon.\n3.Put both seeds and pod in the pan.\n4.Stir the mixture over medium heat until sugar completely dissolves.\n5.Remove from the heat and add the vanilla extract, the rest of the heavy cream (1 cup) and milk. Mix well.\n6.Chill the mixture in the refrigerator for several hours (or overnight) until completely cold.\n7.Pit cherries. By the way, a cherry pitter is a great investment ($13) if you have small children who loves cherries or you enjoy making cherry desserts every year - its super quick to pit cherries!\n8.Cut cherries into quarters.\n9.Take out the vanilla bean pod before churning. Process the mixture in your ice cream maker according to manufacturers instructions (about 25 minutes). Or follow.\n10.In last 5 minutes add in the cherries. My ice cream maker bowl is 1.5 QT so I had to stop churning and add cherries. Combine ice cream and cherries well.\n11.Put the ice cream in an airtight container and let it firm by freezing it for several hours. ', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(7, 'Chocolate almond ice cream', 'images/Chocolate almond ice cream(300x300).jpg', '\n2 envelopes unflavored gelatin.\n6 tablespoons cold water.\n3 cups milk.\n3 cups sugar.\n1/4 teaspoon salt.\n3 eggs, lightly beaten.\n6 to 7 ounces unsweetened chocolate, melted.\n4 cups heavy whipping cream.\n2 teaspoons vanilla extract.\n1 cup sliced or slivered Diamond of California® Almonds, toasted', '\n1.In a small bowl, sprinkle gelatin over cold water; let stand for at least 2 minutes. In a large heavy saucepan, heat the milk, sugar and salt until bubbles form around sides of pan. Whisk a small amount of hot mixture into the eggs. Return all to the pan, whisking constantly.\n2.Cook and stir over low heat until mixture is thickened and coats the back of a spoon. Remove from the heat. Stir in gelatin mixture until dissolved; stir in chocolate until blended. Cool quickly by placing pan in a bowl of ice water; stir for 2 minutes. Stir in cream and vanilla. Press plastic wrap onto surface of custard. Refrigerate for several hours or overnight.\n3.Fill cylinder of ice cream freezer two-thirds full; freeze according to manufacturers directions. Refrigerate remaining mixture until ready to freeze. When ice cream is frozen, stir in almonds. Transfer to a freezer container; freeze for 2-4 hours before serving.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(8, 'Chocolate chip ice cream', 'images/Chocolate chip ice cream(300x300).jpg', '\n300ml ½ pt full-cream milk.\n6 medium organic egg yolks.\n150g 5oz caster sugar.\n1 tsp vanilla extract.\n350ml 12fl oz double cream.\n30g 1¼ oz dark chocolate about 70 per cent cocoa', '\n1.Pour the milk into a small pan and bring to the boil. Whisk the egg yolks and sugar in a bowl, then whisk in the milk. Return the mixture to the pan and heat gently until you have a thin pouring custard that coats the back of the spoon, taking care not to overheat it. Pour it straight away through a sieve into a clean bowl, stir in the vanilla, cover the surface with clingfilm and leave to cool, then chill.\n2.Using an electric whisk, whip the double cream until it forms soft fluffy peaks and fold it into the custard. Coarsely grate the chocolate.\n3.If using an ice-cream maker, freeze according to manufacturer’s instructions, scattering over the grated chocolate a few minutes before the end. Eat straight away, or transfer to a container, cover and freeze until required.\n4.Alternatively, use a food processor. First pour the ice-cream mixture into a container, seal and freeze until softly frozen (start checking after about 3 hours, and hourly thereafter). Scoop the soft ice cream into the bowl of a food processor and whiz to a thick slush. Spoon back into the container, scatter over and fold in the grated chocolate, seal and return it to the freezer for another few hours or overnight.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(9, 'Chocolate ice cream', 'images/Chocolate ice cream(300x300).jpg', '\n1 1/2 cups heavy cream.\n1 1/2 cups whole milk.\n1/2 cup unsweetened cocoa powder.\n4 ounces semisweet chocolate, finely chopped.\n4 large egg yolks.\n3/4 cup granulated sugar.\n1 teaspoon vanilla extract', '\n1.Prepare an ice water bath by filling a large bowl halfway with ice and water; set aside. Set a fine-mesh strainer over a large heatproof bowl and set aside.\n2.Combine cream and milk in a large saucepan and bring to a simmer over medium heat. Remove from heat and whisk in cocoa powder until incorporated. Add chocolate and whisk until completely melted and smooth; set aside.\n3.Whisk egg yolks in a large bowl until smooth. Gradually add sugar and whisk until mixture is pale yellow and thickened, about 3 minutes. Slowly pour about a quarter of the chocolate mixture into the egg mixture, whisking constantly so the hot mixture doesn’t scramble the eggs.\n4.Pour chocolate-egg mixture back into the saucepan. Cook over low heat, stirring constantly with a wooden spoon, until the mixture thickens slightly and coats the spoon, about 5 minutes. (When you draw your finger across the spoon, it should make a mark through the mixture, which should not run back in on itself).\n5.Remove from heat and strain through the prepared fine-mesh strainer. Stir vanilla extract into the chocolate base, then set the bowl over the ice bath to cool to room temperature, about 15 to 20 minutes.\n6.Remove the chocolate base from the ice bath, cover, and place in the refrigerator until completely chilled, at least 3 hours or overnight. Freeze in an ice cream maker according to the manufacturer’s instructions. The ice cream will keep in an airtight container in the freezer for up to 1 week', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(10, 'Chocolate truffle ice cream', 'images/Chocolate truffle ice cream(300x300).jpg', '\n1/2 cup sugar.\n2 large egg yolks.\n1 cup milk.\n1/4 cup cocoa powder.\n1 1/2 cups heavy cream.\n6 ounces bittersweet chocolate, chopped.\n1 teaspoon vanilla extract', '\n1.In a small mixing bowl, beat the sugar into the egg yolks until thickened and pale yellow. Set aside.\n2.Bring the milk to a simmer in a heavy medium saucepan. Whisk in the cocoa and bring the milk back to a simmer. Simmer 3 minutes, stirring constantly. Slowly beat the hot milk and cocoa into the eggs and sugar. Pour the entire mixture back into the pan and place over low heat. Stir constantly with a whisk or wooden spoon until the custard thickens slightly. Be careful not to let the mixture boil or the eggs will scramble. Remove from the heat and pour the hot chocolate custard through a strainer into a large, clean bowl. Set aside while you prepare the ganache.\n3.Bring the cream to a simmer in a small saucepan. Immediately remove from the heat and pour the cream over the chopped chocolate in a bowl. Stir until the chocolate is melted and the mixture is smooth. Combine the chocolate mixtures, then stir in the vanilla. Cover and refrigerate until cold or overnight.\n4.Stir the chilled custard, then freeze in 1 or 2 batches in your ice cream machine according to the manufacturers instructions. When finished, the ice cream will be soft but ready to eat. For firmer ice cream, transfer to a freezer-safe container and freeze at least 2 hours.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(11, 'Coffee ice cream', 'images/Coffee ice cream(300x300).jpg', '\n1 1/2 cups whole milk.\n3/4 cup sugar.\n1 1/2 cups whole coffee beans (decaf unless you want the caffeine in your ice cream).Pinch of salt.\n1 1/2 cups heavy cream.\n5 large egg yolks.\n1/4 teaspoon vanilla extract.\n1/4 teaspoon finely ground coffee (press grinds through a fine mesh sieve)', '\n1 Heat the milk, sugar, whole coffee beans, salt, and 1/2 cup of the cream in a medium saucepan until it is quite warm and steamy, but not boiling. Once the mixture is warm, cover, remove from the heat, and let steep at room temperature for 1 hour.\n2 Pour the remaining 1 cup of cream into a medium size metal bowl, set on ice over a larger bowl. Set a mesh strainer on top of the bowls. Set aside.\n3 Reheat the milk and coffee mixture, on medium heat, until again hot and steamy (not boiling!). In a separate bowl, whisk the egg yolks together. Slowly pour the heated milk and coffee mixture into the egg yolks, whisking constantly so that the egg yolks are tempered by the warm milk, but not cooked by it. Scrape the warmed egg yolks back into the saucepan.\n4 Stir the mixture constantly over medium heat with a heatproof, flat-bottomed spatula, scraping the bottom as you stir, until the mixture thickens and coats the spatula so that you can run your finger across the coating and have the coating not run. This can take about 10 minutes.\n5 Pour the custard through the strainer and stir it into the cream. Press on the coffee beans in the strainer to extract as much of the coffee flavor as possible. Then discard the beans. Mix in the vanilla and finely ground coffee, and stir until cool.\n6 Chill the mixture thoroughly in the refrigerator, then freeze it in your ice cream maker according to the manufacturers instructions.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(12, 'Fruit and nut ice cream', 'images/Fruit and nut ice cream(300x300).jpg', '\n55g (1/3 cup) hazelnuts, cut in half.\n25g (1/4 cup) flaked almonds.\n80g dried peaches, chopped.\n60g dried whole dessert figs, chopped.\n55g (1/4 cup) pistachio kernels.\n1L container Connoisseur Super Premium.\nClassic Vanilla ice-cream', '\nStep 1: Preheat oven to 180°C. Line an 11 x 21cm (base measurement) loaf pan with 2 layers of plastic wrap, allowing it to overhang.\nStep 2: Spread the hazelnuts and almonds over a baking tray and cook in preheated oven for 3-4 minutes or until light golden. Place the hazelnuts in a tea towel and rub to remove the skin. Transfer the hazelnuts and almonds to a medium bowl. Add the peaches, figs and pistachio kernels, and stir until well combined.\nStep 3: Sprinkle the fruit and nut mixture over the base of the prepared pan. Spoon the ice-cream over the nut mixture and use the back of a spoon to smooth the surface. Cover with a double layer of plastic wrap and place in freezer for 6 hours or overnight until firm.\nStep 4: To make the toffee cream, place the sugar in a medium frying pan over low heat and cook, stirring, for 3 minutes or until it turns golden brown. Remove pan from heat and gradually stir in the cream (the toffee will harden). Place pan over low heat and cook, stirring, for 2-3 minutes or until toffee dissolves and sauce is smooth. Remove from heat and set aside for 5 minutes to cool slightly.\nStep 5: Turn ice-cream onto a serving platter. Remove plastic wrap and cut into 2.5cm-thick slices. Serve immediately with the toffee cream.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(13, 'Kiwi fruit ice cream', 'images/Kiwi fruit ice cream(300x300).jpg', '\n568ml carton double cream.\n300ml whole milk.\n6 large egg yolks, plus 1 egg white.\n100g caster sugar.\nGrated zest of 1 lemon.\n6 large ripe kiwi fruits.\nIcing sugar to taste', '\n1.Heat the cream and milk together in a heavy-based pan to just below boiling point. Meanwhile, beat the egg yolks and sugar together in a bowl until thick and creamy. Pour the hot cream mixture on to the egg yolk mixture, whisking constantly. Return the mixture to the pan and heat gently, stirring, until the custard thickens enough to lightly coat the back of a wooden spoon - 10-12 minutes. Strain into a clean bowl, add the lemon zest and leave to cool. At this stage, you can chill the custard for a few hours before continuing.\n2.Top and tail the kiwi fruits and remove the skin. Cut the fruit into quarters, remove the white centre then purée the fruit in a blender. Make a thick pad out of layers of kitchen paper. Pour the purée on to the paper and leave for 2-3 minutes to absorb the water from the fruit.\n3.Mix the kiwi purée into the custard. If the mix tastes tart, sweeten with a little icing sugar (the ice cream will taste even less sweet when frozen).\n4.Process the custard in an ice cream maker until thick and holding its shape. Transfer to a freezer container. Alternatively, pour the custard into a freezer container, cover, freeze for 2 hours and whisk well to break up the ice crystals. Return to the freezer. Repeat the twice more or until the ice cream is very thick and holds its shape.\n5.Whisk the egg white until it holds soft peaks. Fold into the thick ice cream. Freeze overnight or until firm.\n6.Remove from the freezer 5 minutes before serving.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(14, 'Mango ice cream', 'images/Mango ice cream(300x300).jpg', '\n1 ripe mango, medium to large.\n2 eggs.\n1 cup sugar.\n1 tsp. vanilla.\n2 cups cream.\n1 to 2 cups milk', '\n1.Peel and slice the mango, choosing a less stringy type of mango, if possible. Place in blender and puree until very smooth. If you start with about 2 cups of pieces, you should have 1 to 1 1/2 cups of puree. If your mango is very large, chop the excess and use to top the ice cream later.\n2.Beat the eggs with a wire whisk for 2 minutes until thick and lemon-colored. Slowly whisk in the sugar, beating about a minute more. Stir in the vanilla, cream, and mango puree. Add enough milk to fill your container to the proper level. For the Cuisinart ice cream maker, 5 to 5 1/4 cups is the maximum.\n3.Chill the mixture very well. Freeze according to your ice cream maker instructions.\n4.If you must, substitute low-fat, no-fat, fake egg, sugar-free stuff, but I take no responsibility for that!', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(15, 'Pineapple ice cream', 'images/Pineapple ice cream(300x300).jpg', '\n2 cups milk.\n1 cup sugar.\n3 eggs, lightly beaten.\n1-3/4 cups heavy whipping cream.\n1 can (8 ounces) crushed pineapple, undrained', '\n1.In a large saucepan, heat milk to 175°; stir in sugar until dissolved. Whisk a small amount of the hot mixture into the eggs. Return all to the pan, whisking constantly. Cook and stir over low heat until mixture reaches at least 160° and coats the back of a metal spoon.\n2.Remove from the heat. Cool quickly by placing pan in a bowl of ice water; stir for 2 minutes. Stir in whipping cream and pineapple. Press waxed paper onto surface of custard. Refrigerate for several hours or overnight.\n3.Fill cylinder of ice cream freezer two-thirds full; freeze according to the manufacturer’s directions. Refrigerate remaining mixture until ready to freeze. When ice cream is frozen, transfer to a freezer container; freeze for 2-4 hours before serving.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(16, 'Pistachio ice cream', 'images/Pistachio ice cream(300x300).jpg', '\n1 C crushed butter-flavored crackers.\n1/4 C butter, melted.\n3/4 C cold milk.\n1 pkg (3.4-oz) instant pistachio pudding mix.\n1 qt. vanilla ice cream, softened.\n1 carton (8-oz) frozen whipped topping, thawed.\n2 pkg (1.4-oz each) Heath candy bars, crushed', '\n1.In bowl, combine cracker crumbs and butter. Press into an ungreased 9-in. square baking pan. Bake at 325 degrees for 7-10 minutes or until lightly browned. Cool on a wire rack.\n2.Meanwhile, in a large bowl, whisk milk and pudding mix for 2 minutes. Let stand for 2 minutes or until soft-set. Stir in ice cream; pour over crust. Cover and freeze for 2 hours or until firm.\n3.Spread with whipped topping; sprinkle with crushed candy bars. Cover and freeze for 1 hour or until firm.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(17, 'Strawberry ice cream', 'images/Strawberry ice cream(300x300).jpg', '\n175 gram(s) caster sugar (plus 2 tablespoons).\n500 ml Full fat milk.\n500 ml double cream.\n1 vanilla pod.\n2 tablespoon(s) lemon juice.\n10 Egg yolks.\n500 gram(s) strawberries', '\n1.Hull and roughly chop the strawberries, put them into a bowl and sprinkle over the 2 tablespoons of caster sugar and leave them to steep and infuse with flavour.\n2.Pour the milk and cream into a heavy-based saucepan, and add the vanilla pod, split down the middle lengthways. Bring the pan nearly to the boil and then take it off the heat and leave to infuse for 20 minutes.\n3.In a large bowl whisk the egg yolks and the 175g sugar until thick and pale yellow. Take the vanilla pod out of the milk and cream and pour, whisking the while, the warm liquid over the yolks. Put the cleaned-out pan back on the heat with the cream, milk, egg and sugar mixture and stir the custard until it thickens, then take it off the heat and pour it into a bowl to cool.\n4.Puree the strawberries in a processor, and when the custard is cool fold in the lemon juice and strawberry puree.\n5.At this point you can either freeze the ice cream in an ice-cream maker, or in a plastic tub in the freezer. If you do the latter you should whip it out every hour for 3 hours as it freezes and give it a good beating, either with an electric whisk, by hand or in the processer. That gets rid of any ice crystals that form and that make the ice cream crunchy rather than smooth.', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(18, 'Vanilla and strawberry ice cream', 'images/Vanilla and strawberry ice cream(300x300).jpg', '\n3/4 Cup sugar.\n1 Cup whole milk (raw if possible).\n1/4 t. salt.\n1 vanilla bean, split and scraped.\n3 egg yolk, lightly beaten.\n2 Cup heavy cream.\n1 Cup finely diced fresh strawberries.\n1/4 Cup sugar', '\n1.Combine sugar, milk, salt, and scraped vanilla bean and pods in a saucepan over low heat.  Stir until the mixture just begins to steam and simmer.   Place the egg yolks into a small bowl. Gradually stir in about 1/2 cup of the hot liquid to temper the eggs and return everything to the saucepan. Heat until thickened, about 5 minutes, but be careful not to boil. Remove from the heat, and pour into a chilled bowl and refrigerate for at least two hours or overnight.\n2.Using a slotted spoon, fish out the vanilla pods from the chilled custard.Whip the heavy cream until it forms soft peaks and gently fold into the custard mixture. Pour into an ice cream maker, and freeze according to manufacturer’s directions.  Meanwhile, combine the diced strawberries with the remaining sugar and set aside.\n3.When ice cream is done churning, scoop out into a container with a lid.  Fold in the strawberries while ice cream is still soft.  Cover container tightly and place in freezer to firm up, about 3-4 hours. ', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(19, 'Vanilla ice cream', 'images/Vanilla ice cream(300x300).jpg', '\n1 cup (250ml) whole milk.\nA pinch of salt.\n3/4 cup (150g) sugar.\n1 vanilla bean, split lengthwise.\n2 cups (500ml) heavy cream.\n5 large egg yolks.\n1 teaspoon pure vanilla extract', '\n1. Heat the milk, salt, and sugar in a saucepan. Scrape the seeds from the vanilla bean into the milk with a paring knife, then add the bean pod to the milk. Cover, remove from heat, and infuse for one hour.\n2. To make the ice cream, set up an ice bath by placing a 2-quart (2l) bowl in a larger bowl partially filled with ice and water. Set a strainer over the top of the smaller bowl and pour the cream into the bowl.\n3. In a separate bowl, stir together the egg yolks. Rewarm the milk then gradually pour some of the milk into the yolks, whisking constantly as you pour. Scrape the warmed yolks and milk back into the saucepan.\n4. Cook over low heat, stirring constantly and scraping the bottom with a heat-resistant spatula, until the custard thickens enough to coat the spatula.\n5. Strain the custard into the heavy cream. Stir over the ice until cool, add the vanilla extract, then refrigerate to chill thoroughly. Preferably overnight.\n6. Remove the vanilla bean and freeze the custard in your ice cream maker according to the manufacturer’s instructions.\nNote: Used vanilla beans can be rinsed and dried, then stored in a bin of sugar. That sugar can be used for baking and, of course, for future ice cream making.M: Soak 1/2 cup raisins in 1/2 cup rum for 30 minutes. When the ice cream is finished, add the raisins and rum and continue cranking until they are mixed in and the ice cream has refrozen. Blend in 1/3 cup chopped toasted walnuts with a spoon or spatula. ', 'Bruce Weinstein', 1, '2012-01-01', 1),
	(20, 'Walnut ice cream', 'images/Walnut ice cream(300x300).jpg', '\n1 quart milk.\n1 quart whipping cream.\n2 cups sugar, divided.\n2 vanilla beans, cut in half lengthwise.\n2 dozen egg yolks.\n2 cups coarsely chopped walnuts, toasted', '\n1.Bring milk, whipping cream, 1 cup sugar, and vanilla beans to a boil in a large, heavy saucepan over medium heat, whisking constantly. Remove from heat.\n2.Whisk together egg yolks and remaining 1 cup sugar in a large bowl. Gradually add one-fourth hot mixture into yolk mixture; whisk back into remaining hot mixture.\n3.Cook over low heat, whisking constantly, 10 to 15 minutes or until mixture thickens.\n4.Pour mixture through a fine wire-mesh strainer into a large bowl, discarding vanilla beans. Immediately set bowl in ice, and let stand, stirring constantly, until cool.\n5.Stir in walnuts.\n6.Pour mixture into the freezer container of a 1-gallon electric freezer. Freeze according to manufacturers instructions.\n7.Pack freezer with additional ice and rock salt, and let stand 1 hour before serving.', 'Bruce Weinstein', 1, '2012-01-01', 1);
/*!40000 ALTER TABLE `recipe` ENABLE KEYS */;

-- Dumping structure for table icecream.reference
CREATE TABLE IF NOT EXISTS `reference` (
  `reference_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `monthly_fee` float NOT NULL,
  `yearly_fee` float NOT NULL,
  `book_cost` float NOT NULL,
  PRIMARY KEY (`reference_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.reference: ~1 rows (approximately)
/*!40000 ALTER TABLE `reference` DISABLE KEYS */;
INSERT INTO `reference` (`reference_id`, `monthly_fee`, `yearly_fee`, `book_cost`) VALUES
	(1, 15, 150, 49.99);
/*!40000 ALTER TABLE `reference` ENABLE KEYS */;

-- Dumping structure for table icecream.user_recipe
CREATE TABLE IF NOT EXISTS `user_recipe` (
  `user_recipe_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `image` varchar(100) NOT NULL,
  `desciption` text NOT NULL,
  `details` text NOT NULL,
  `customer_id` bigint(20) NOT NULL,
  `prize_status` tinyint(1) NOT NULL DEFAULT 0,
  `enable_status` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_recipe_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- Dumping data for table icecream.user_recipe: ~10 rows (approximately)
/*!40000 ALTER TABLE `user_recipe` DISABLE KEYS */;
INSERT INTO `user_recipe` (`user_recipe_id`, `name`, `image`, `desciption`, `details`, `customer_id`, `prize_status`, `enable_status`) VALUES
	(1, 'Ice Cream on Sticks', 'images/userrecipe/Ice Cream on Sticks.jpg', '1 cup orange juice \nBowl of whipped cream\nSmall glasses\n5 ice cream sticks\nVanilla essence', 'This is a very simple recipe to make ice cream on sticks. I have taken orange juice here, you can go in for any flavor you like. It could be strawberry juice, pomegranate is a good option and so is cranberry. Whatever juice you decide; pour it in small glasses and place a stick in there. Refrigerate it until it is converted into ice. Now, to the bowl of whipped cream add a few drops of vanilla essence and beat it, until it develops a thick consistency. Pour it over the ice candy and enjoy it to the fullest. Ice candies would serve as a very good dessert idea for your kids birthday party as well. They are also a healthy option, as they have less fats compared to the normal ice cream.', 1, 1, 1),
	(2, 'Chocolate Soy Milk Ice Cream', 'images/userrecipe/Chocolate Soy Milk Ice Cream.jpg', 'Soy milk, 3 cups\nCocoa powder, 2 to 3 teaspoons\nPowdered sugar, 1 cup\nCornstarch, 1½ teaspoons\nVanilla bean or vanilla essence, 1 teaspoon\nEgg yolks', 'Take a large bowl and beat the egg yolks along with the cornstarch and powdered sugar. Heat the soy milk in a medium-sized saucepan, making sure that it does not boil. Add the cocoa powder to the milk and stir till it incorporates into the milk. Once the milk has warmed, pour this into the egg mixture, all the while, whisking it. Add the vanilla essence and continue to stir it. Now transfer the contents of the bowl to the same saucepan and warm it till the mixture becomes thick. Pour the mixture into a separate bowl and place it in a refrigerator for about a couple of hours to chill it. Pour this chilled mixture into a soy milk ice cream maker and process it. Scoop out the ice cream and serve it with freshly cut fruits, of your choice.', 2, 1, 1),
	(3, 'Ice Cream with Coconut', 'images/userrecipe/Ice Cream with Coconut.jpg', '3 cups coconut milk\n3 tbsp honey\n2 cups blueberries', 'In a blender, blend blueberries till they are smooth.\nAdd coconut milk and honey to the blueberry puree.\nPour the ice cream mixture in a bowl and let it chill for about 2 to 4 hours.\nNow the mixture can be placed in an ice cream maker and follow the instructions on the ice cream maker to get smooth coconut milk ice cream.', 3, 1, 1),
	(4, 'Non Dairy Ice Cream', 'images/userrecipe/Non Dairy Ice Cream.jpg', '5 cups soy milk or almond milk or coconut milk\n2 cup soy milk powder\n½ cup cocoa powder\n1 ½ cups sugar\n1 cup powdered sugar\n1 tbsp cider vinegar', 'Blend soy milk with soy milk powder and vinegar till all the ice cream ingredients are well mixed.\nPour the soy milk mixture in a saucepan and add sugar and powdered sugar to it, along with the cocoa powder. Let the mixture come to a boil over medium-low heat.\nWhen the mixture is coming to a boil, ensure you continue to stir constantly.\nLet the mixture cook till it is thick and syrupy. It should resemble a pudding.\nThen pour the mixture in a metal pan and place it in the freezer without covering it for about an hour.\nOnce the mixture thickens, remove the pan from the freezer and scrap it and place it in a blender.\nBlend the mixture on high for 30 to 40 seconds, so that the mixture is creamy.\nNow pour the mixture in a pan and place it back in the freezer.\nYou will have to repeat the procedure 3 times after every 30 to 45 minutes, after which let the ice cream freeze for an hour and half before you serve it.\nYou can add toppings of your choice, if you want to, on this ice cream.', 1, 0, 1),
	(5, 'Almond Milk Ice Cream', 'images/userrecipe/Almond Milk Ice Cream.jpg', 'Almond milk - 2.5 cups\nEgg yolks - 8\nSugar - 1.25 cups\nVanilla extract - 2 teaspoons\nHeavy cream - 1.5 cups', 'Start with heating almond milk and heavy cream in a sauce pan placed over medium heat. Once the mixture boils, cook at low temperature for a few minutes and remove from heat. In another bowl, beat the egg yolks and when it is half done, add sugar and whisk thoroughly. Once done, slowly add the almond milk-cream mixture to the egg-sugar mixture in small amounts. Make sure to stir constantly, so that the eggs do not get cooked with the hot milk. Once the whole milk is added, transfer the contents of the bowl to the sauce pan. Once again, place it on medium heat and cook till a temperature of 175° F is reached. Remove from heat and place the saucepan in an icebox so as to cool the contents as soon as possible. Add the vanilla extract and allow the mixture to cool below 40 degree Fahrenheit. If you have an almond milk ice cream maker, you can use it to churn this mixture. Otherwise, use the ice cream mixing bowl of the mixer and run it for at least 30 minutes. Once done, freeze this mixture, before serving, so that it gets the consistency of regular ice cream.', 2, 0, 1),
	(6, 'Low-carb Ice Cream', 'images/userrecipe/Low-carb Ice Cream.jpg', 'Vanilla essence, 3 tsp.\nAny commercial artificial sweetener, 10 tsp.\nUnflavored gelatin, 2 tbsp.\nAny commercial egg replacer, 8 oz\nCold skim milk, ½ cup\nFat free powdered milk, 2 cups', 'Take a dry saucepan and mix the powdered milk and gelatin together. Place over a low flame and stir gently and continuously till the gelatin is completely dissolved and you get an even mixture.\nRemove the saucepan from the flame and set aside to allow it to cool down to room temperature.\nBlend all the remaining ingredients in a food processor till they are evenly combined and the mixture has a fine texture.\nOnce the milk-gelatin mixture has cooled down sufficiently, add it to the other ingredients and blend again for a couple of minutes.\nRefrigerate the entire mixture till its just about to freeze. Blend for a few seconds.\nPass it through a strainer into the ice cream maker and freeze as instructed therein.', 3, 0, 1),
	(7, 'Sugar-free Ice Cream', 'images/userrecipe/Sugar-free Ice Cream.jpg', 'Gelatin\nLow fat milk\nSugar sweeteners\nChocolate drink mix or cocoa powder (you can use flavor or essence of your choice say vanilla or strawberry or mango etc.)\nSalt\nBlender\nSaucepans\nBowls\nEggs (optional)', 'Add gelatin to half a cup of low fat milk in a saucepan and heat until the gelatin softens and is fully mixed.\nKeep the mixture in cold water in a bowl, until it cools down.\nAdd rest of the milk, sugar sweetener, ice cream essence and flavor and a pinch of salt to the mixture and blend it.\nChill the mixture in refrigerator and then add in the ice cream maker. Make sure that the blending is proper; its the most important step in ice cream making.\nFreeze until the ice cream is set properly. Follow the manufacturers instructions for the same.\nYour sugar-free ice cream is ready to eat!\nWhile for eggs, beat them properly and then add during blending.', 1, 0, 1),
	(8, 'Fried Ice Cream', 'images/userrecipe/Fried Ice Cream.jpg', 'Vanilla Ice Cream 1 quart\nCrushed Frosted Cornflakes 1 cup\nCookie Crumbs 1 cup\nEggs 2\nSugar 2 tablespoons\nVegetable Oil for frying\nHot Chocolate Sauce\nWhipped Cream', 'With the ice cream, form 4 large balls of ice cream, wrap them in waxed paper and cover with plastic wrap to freeze them for at least 2 to 3 hours.\nIn a bowl, combine cornflakes and cookie crumbs and spread the mixture in a shallow dish.\nDip the ice cream balls in the cornflakes mixture and freeze again for 30 minutes.\nBeat eggs and sugar in a bowl.\nDip the ice cream balls in the eggs and roll them again in the crumb mixture and make sure that the balls are well coated.\nYou will have to freeze the ice cream balls again for an hour or longer.\nHeat oil to 400 degrees Fahrenheit and lower the balls into the oil and fry them till the balls are golden brown in color.\nRemove the ice cream balls and place them on a dessert bowl, drizzle some chocolate sauce and whipped cream on it and serve.', 2, 0, 1),
	(9, 'Cupcake Ice Cream', 'images/userrecipe/Cupcake Ice Cream.jpg', '2 cups self-raising flour\n1 cup sugar\n½ cup unsalted butter\n3 eggs\n1 teaspoon baking powder\n1 teaspoon vanilla extract\n½ cup milk\n½ teaspoon salt\nAssorted candy sprinkles\n¼ cup chopped roasted pistachios\n12 cherries\n1 cup whipping cream\n½ cup icing sugar\nFood color (optional)\n12 flat bottomed ice cream cones', 'In a large bowl, sift the self-raising flour with the baking powder and the salt. In another bowl whisk the eggs, milk, sugar and butter. Pour this mixture in the bowl containing the dry ingredients. Whisk all this together along with a tablespoon of vanilla extract until everything is well blended. Now when your cupcake batter is ready, fill each cone with 2 to 3 tablespoons of this batter. Bake in an oven at 220º centigrade for 20 to 25 minutes. Remove from the oven and let it cool completely.\nBeat the whipping cream until stiff peaks are formed. Add in the icing sugar and whip this mixture until all the sugar has been dissolved. Put half a tablespoon of food coloring if you wish. Fill a pastry bag with this icing and pipe it on top of the cupcake cones. Decorate the ice cream cones with assorted candy sprinkles, chopped roasted pistachios and cherries.', 3, 0, 1),
	(10, 'Classic Chocolate Ice Cream', 'images/userrecipe/Classic Chocolate Ice Cream.jpg', 'Milk, 1 cup\nGranulated sugar, ½ cup\nBittersweet/semi-sweet chocolate,1⅓ cup\nHeavy cream, 2 cups\nVanilla extract,1 tsp', 'Heat milk in a stove or microwave until it just begins to bubble. Meanwhile, process chocolate in a food processor or blender until the chocolate is finely chopped. Mix chocolate and sugar. Combine hot milk and chocolate mixture and blend until chocolate is melted and the mixture is smooth. Cool the mixture. Once you have done that, stir in heavy cream and vanilla. Chill for at least 30 minutes. Pour mixture into your ice cream maker. Mix in ice cream machine for 25 - 30 minutes or according to manufacturers instructions.', 1, 0, 1);
/*!40000 ALTER TABLE `user_recipe` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
