name: "Chronos service script"

on:
  workflow_dispatch:
    inputs:
      ENV:
        type: choice
        options: [DEV, STAG, PROD]
        required: true
        default: DEV

run-name: "[${{ inputs.ENV }}](🚀): chronos-service"

jobs:
  build:
    name: Build Icecream Chronos Service (${{ inputs.ENV }})
    uses: ./.github/workflows/build-spring-boot-service.yaml
    with:
      root-path: icecream-system
      module: chronos
      image-name: icecream-chronos-service
      ENV: ${{ inputs.ENV }}
    secrets: inherit
