name: Storefront script

on:
  workflow_dispatch:
    inputs:
      ENV:
        type: choice
        options:
          - DEV
          - STAG
          - PROD
        default: DEV
        required: true

run-name: "[${{ inputs.ENV }}](🚀): storefront"

jobs:
  build:
    name: Build Icecream Storefront (${{ inputs.ENV }})
    uses: ./.github/workflows/build-nextjs.yaml
    with:
      root-path: icecream-ui/storefront
      image-name: icecream-storefront
      ENV: ${{ inputs.ENV }}
    secrets: inherit
